nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin:
            - '^http://localhost:3000$'
            - '^http://localhost:5173$'
            - '^http://www\.carcarenow\.es(:[0-9]+)?$'
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/': ~
